services:
  - type: web
    name: rakshika-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm run server
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production

